# Generated by Django 4.2.24 on 2026-02-18 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rfq'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('specifications', models.TextField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=200)),
                ('timeline', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RFQ',
        ),
    ]
