# Generated by Django 4.2.24 on 2026-02-20 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_quotationrequest_delete_rfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_tickets/'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='category',
            field=models.CharField(choices=[('order_issue', 'Order Issue'), ('shipping', 'Shipping & Delivery'), ('payment', 'Payment Issue'), ('product_quality', 'Product Quality'), ('return_refund', 'Return & Refund'), ('technical', 'Technical Support'), ('general', 'General Inquiry')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='subject',
            field=models.CharField(default='low', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
